export enum LocalizationKey {
  WELCOME = "welcome",
  HOME = "home",
  START = "start",
  LOADING = "loading",
  LOGIN = "login",
  SIGNUP = "signup",
  FORGOTPASSWORD = "forgotpassword",
  SIGNUPWITH = 'signupwith',
  CREATEACCOUNT = 'createaccount',
  USERNAME = 'username',
  EMAIL = 'email',
  PHONENUMBER = 'phonenumber',
  PASSWORD = 'password',
  BOOK = 'book',
  // Booking
  CHOOSESTARTPOS = 'choosestartpos',
  CHOOSEENDPOS = 'chooseendpos',
  CHOOSEDATE = 'choosedate',
  CHOOSEBUSLINE = 'choosebusline',
  TICKETINFO = 'ticketinfo',
}
