export enum RootScreens {
  MAIN = "Main",
  WELCOME = "Welcome",
  SIGNUP = "Signup",
  LOGIN = "Login",
  BOOKING = 'Booking',
  WELCOME1 = "Welcome1",
  WELCOME2 = "Welcome2",
  ACCOUNT = "Account",
  ACCOUNT_NOT_LOGIN = "AccountNotLogin",
  ACCOUNT_DETAIL = "AccountDetail",
  REPORT = "Report",
  REPORT_RESULT = "ReportResult",
  PICK_START = "PickStart",
  PICK_END = "PickEnd",
  PICK_BUSLINE = "PickBusline",
  BUS_BOOKING = "BusBooking",
  HOTLINE = "Hotline",
  ROUTE = "Route",
  TICKET_INFO = "TicketInfo",
  HISTORY = "History",
  BUS = "Bus",
  SEARCH = "Search"
}
